### ISSUE TITLE
Problems encountered using sen2nbar

### ISSUE THREAD

**Issue by zhongguolishenglin** [ESDS-Leipzig/sen2nbar#2]
I tried it with this instruction
![image](https://user-images.githubusercontent.com/114329649/233332870-537620a7-33c8-4a4d-90c4-9bd44b867bbf.png)
I installed the corresponding package, but could not run the result
![image](https://user-images.githubusercontent.com/114329649/233333251-640f1021-11f9-456f-bfd4-e5186554b8a1.png)
![image](https://user-images.githubusercontent.com/114329649/233333274-e7f9f421-b8e8-455f-9e5b-4335299234f9.png)
![image](https://user-images.githubusercontent.com/114329649/233333304-94f4897e-8b92-48d1-8b13-12a47107fb4c.png)

**Comment by davemlz** [comment]
Hi @zhongguolishenglin!

This bug corresponds to the same one informed at #4. Please refer to that Issue for information on the fiz advancements.

Best,

David
