### ISSUE TITLE
String parsing error in Windows

### ISSUE THREAD

**Issue by behzad-vahedi** [ESDS-Leipzig/sen2nbar#4]
Running the `nbar_SAFE()` function in Windows results in the following error:
`rasterio._err.CPLE_OpenFailedError: Attempt to create new tiff file '...' failed in VSI_TIFFOpen().`

After further investigation, I realized it is caused by a platform-dependent string parsing in nbar.py (the following line). 
` filename = img_path.split("/")[-1].replace("jp2", "tif")`

I would suggest a quick fix like this:
```python
if os.name == 'nt':  # Windows
    dir_sep = "\\"
else:  # Linux, macOS, and other platforms
    dir_sep = "/"
filename = img_path.split(dir_sep)[-1].replace("jp2", "tif")
```

**Comment by davemlz** [comment]
You are totally right!

I will correct this now.

Best,

David

**Comment by davemlz** [comment]
This was fixed!

It will be available in the next version of sen2nbar!

Best,

David
